### ISSUE TITLE
Problem with COPY and REFERENCE in models.py

### ISSUE THREAD

**Issue by RainerPopella** [signalkraft/myPyllant#11]
In models.py you use:
    _state = [c for c in self.state.get(obj_name, []) if c["index"] == idx][0]_
This will give you a reference to the original object. 
The command _del state["index"]_ will delete the field index in the original object and the program will crash.

To fix the problem you should use:
    _state = dict([c for c in self.state.get(obj_name, []) if c["index"] == idx][0])_ 
This will give you a copy of the original object.

My solution:

    def _merge_object(self, obj_name) -> Iterator[dict]:
        indexes = [o["index"] for o in self.configuration.get(obj_name, [])]
        for idx in indexes:
            configuration = dict([
                c for c in self.configuration.get(obj_name, []) if c["index"] == idx
            ][0])
            state = dict([c for c in self.state.get(obj_name, []) if c["index"] == idx][0])
            properties = dict([
                c for c in self.properties.get(obj_name, []) if c["index"] == idx
            ][0])
            del state["index"]
            del properties["index"]
            logger.debug(
                f"Merging {obj_name} into results: {json.dumps(configuration, indent=2)}"
            )
            logger.debug(json.dumps(state, indent=2))
            logger.debug(json.dumps(properties, indent=2))
            merged = dict(**state, **properties, **configuration)			
            yield merged

**Comment by RainerPopella** [comment]
Hi,
with the new version and with a new version from Vaillant the program will not run into this problem. That's because the function will be called only with one index / set of data. But from my point of view it would be better to fix the function.
Do you found in der messages a version number? So we notice that Vaillant has chaged the App ...
KR Rainer

**Comment by signalkraft** [comment]
@RainerPopella thanks for the issue + PR. You're right about the reference vs copy. I changed how the function works in this commit: https://github.com/signalkraft/myPyllant/commit/65c20ce65df510bca7f7933f1c42731fa74a60d0

This should avoid the issue altogether, since I don't need to `del` anything anymore.

**Comment by RainerPopella** [comment]
Hello,
Sorry for the delay but I was busy with another urgent case :-(

First of all, I like your way of programming. It's really good and "Pythonic". However, this also means that you have to look very carefully at how something is used.

I checked the changes and it looks fine to me. I'm assuming that using the next() function is just to make it easier to handle special cases. Because I see no need for a generator at this point.

I see a note about deepcopy(), but note that next() doesn't do a deepcopy. I checked your implementation and currently you have a big data structure with different views. A change becomes visible in all associated objects. If this is not your intention, you must use deepcopy() in the return (yield) of the function.

Please let me know if I'm wrong.

Can you please send me a brief description of your development environment as I will set up a new one on Linux?

KR Rainer

**Comment by signalkraft** [comment]
Thanks for checking, and good catch on the deepcopy comment. I changed the implementation and didn't update the comment.

> I'm assuming that using the next() function is just to make it easier to handle special cases. Because I see no need for a generator at this point.

`next(i for i in l if i['key'] == 'sth')` is the simplest way I could think of that lets me filter a list of dicts by a key.

> Can you please send me a brief description of your development environment as I will set up a new one on Linux?

I would recommend Ubuntu, since there's a lot of documentation out there and it's easy to set up. You could also go with WSL on Windows. Then just follow https://github.com/signalkraft/myPyllant#contributing

As an editor I would recommend PyCharm Community Edition for Python projects. In my experience, it works better for Python projects out of the box than VS Code.
