### ISSUE TITLE
Unknown state after changing opereting mode to "Cooling for several days"

### ISSUE THREAD

**Issue by MP14588** [signalkraft/myPyllant#8]
Good morning,
the integration worked fine until i changed the operating mode from winter to summer. In particular, for the summer period, I have to set the operating mode to "Cooling for several days". Since that day, the sensors of entity "SENSOconfort" are in an unknown state. I attach the log below.

Thanks a lot.

[log.txt](https://github.com/signalkraft/myPyllant/files/11642550/log.txt)

**Comment by CommanderROR9** [comment]
This seems to be a general issue. For me the integration stopped working entirely as soon as cooling mode kicked in.

**Comment by signalkraft** [comment]
@MP14588 @CommanderROR9 this should be fixed in the latest release (+ the latest beta release of the Home Assistant component)

**Comment by CommanderROR9** [comment]
It seems to be working a bit better now in terms of entities and modes, instead the method to change the hot water temperature has somehow changed. It broke my automation, but I think I found a way to make it work again by using the hot water entity instead of the device...🤷‍♂️
Since myVaillant itself is terribly limited and unreliable it's rather difficult to say where the issue lies exactly...might my myVaillant or the Integration.
